---
- name: make devel dir
  file:
    path: "/home/{{ user.name }}/devel"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0755
    state: directory

- name: make bin dir
  file:
    path: "/home/{{ user.name }}/bin"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0755
    state: directory

- name: hush login messages
  copy:
    content: ""
    dest: "/home/{{ user.name }}/.hushlogin"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0644
